In [1]:
import pandas as pd

In [4]:
data = pd.read_csv("./DATA/pakistanClean2.csv")
data.head()

,eventid,iyear,imonth,iday,region,region_txt,provstate,city,latitude,longitude,...,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related,Date,Month,TTP
0,200712030005,2007,12,3,6,South Asia,Balochistan,Qilla Abdullah district,30.803630,66.711752,...,NaN,CETIS,-9,-9,0,-9,NaN,2007-12-03,Dec,NaN
1,200712040005,2007,12,4,6,South Asia,Khyber Pakhtunkhwa,Peshawar,34.006004,71.537430,...,NaN,CETIS,-9,-9,0,-9,NaN,2007-12-04,Dec,NaN
2,200712060008,2007,12,6,6,South Asia,Balochistan,Dera Bugti,29.034412,69.158661,...,NaN,CETIS,0,0,0,0,NaN,2007-12-06,Dec,0.0
3,200712080003,2007,12,8,6,South Asia,Balochistan,Khuzdar,27.809921,66.620956,...,NaN,CETIS,-9,-9,0,-9,NaN,2007-12-08,Dec,NaN
4,200712090002,2007,12,9,6,South Asia,Balochistan,Nasirabad,28.458421,68.133223,...,NaN,CETIS,-9,-9,0,-9,NaN,2007-12-09,Dec,NaN

In [7]:
train_data = data[(data['TTP']==0) | (data['TTP'] ==1)]
train_data.to_csv('./DATA/pak_train_data.csv', index=False)

In [8]:
test_data = data[pd.isna(data['TTP'])]
test_data.to_csv('./DATA/pak_test_data.csv', index=False)